# Generated by Django 3.2 on 2022-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0002_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_text',
        ),
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.URLField(default='', max_length=300, unique=True),
        ),
    ]
