# Generated by Django 3.2 on 2022-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0003_auto_20220118_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='time_create',
        ),
        migrations.AddField(
            model_name='request',
            name='time_request',
            field=models.DateField(default='2022-01-18'),
        ),
    ]
