# Generated by Django 3.2 on 2022-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0004_auto_20220118_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
