# Generated by Django 3.2 on 2022-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0005_alter_request_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(),
        ),
    ]
