# Generated by Django 3.2 on 2022-01-18 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0007_alter_request_time_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
