# Generated by Django 3.2 on 2022-01-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0008_alter_request_time_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(),
        ),
    ]
