# Generated by Django 3.2 on 2022-01-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0009_auto_20220119_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(default='2022-01-19 21:33'),
        ),
    ]
