# Generated by Django 3.2 on 2022-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0010_alter_request_time_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(default='2022-01-20 13:42'),
        ),
    ]
