# Generated by Django 3.2 on 2022-01-21 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0011_alter_request_time_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 11, 14, tzinfo=utc)),
        ),
    ]
