# Generated by Django 3.2 on 2022-01-21 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MakeTimeRequest', '0012_auto_20220121_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_request',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 19, 36, tzinfo=utc)),
        ),
    ]
